version: '3.8'
services:
  backend:
    build:
      context: backend
      dockerfile: backend.Dockerfile
    command: go run main.go
    tty: true
    volumes:
      - ./backend:/go/src
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - "db:database"
  frontend:
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/frontend/
    stdin_open: true
    # ホットリロード設定
    environment:
     - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
  db:
    image: mysql:8.0
    container_name: MYSQL
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=MYSQL"
      - "MYSQL_USER=MYSQL"
      - "MYSQL_PASSWORD=MYSQL"
      - "MYSQL_DATABASE=MYSQL"
      
