version: '3.8'
services:
  backend:
    build:
      context: backend
      dockerfile: backend.Dockerfile
    command: go run main.go
    tty: true
    volumes:
      - ./backend:/go/src
    ports:
      - "8080:8080"
  frontend:
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/frontend/
    stdin_open: true
    # ホットリロード設定
    environment:
     - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
